baseURL = "https://www.patrickli.one" # The URL of your site
languageCode = "en-gb" # The language you want to display the site in
title = "Baichuan Li" # The title you want to appear in the address bar
theme = "hugo-developer-portfolio" # The theme, don't change this

[params.plugins]
  # CSS Plugins
  [[params.plugins.css]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/css/uikit.min.css"
  # JS Plugins
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit.min.js"
  [[params.plugins.js]]
  URL = "https://cdn.jsdelivr.net/npm/uikit@3.2.6/dist/js/uikit-icons.min.js"

# navigation
[menu]
  [[menu.main]]
  name = "About"
  URL = "about"
  [[menu.main]]
  name = "Blog"
  URL = "blog"
  [[menu.main]]
  name = "Portfolio"
  URL = "portfolio"
  [[menu.main]]
  name = "Contact"
  URL = "contact"


[markup.goldmark.renderer]
    unsafe= true
[params]
home = "Home" # What you want the homepage to show up as in the menu bar
# Meta data
description = "Portfolio of Baichuan Li" # The description of your site
author = "Baichuan Li"


    [params.contact]
    formAction = "https://formspree.io/f/xqkjdalw"

    # This contains the contact information for the footer
    [params.footer]
    email = "public@patrickli.one"
    address = "University of Michigan, Ann Arbor"
    googlemaps = "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2952.0643855713524!2d-83.74078202318752!3d42.27714894033454!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x883cae38e7de1701%3A0x5ba14e5178e997e3!2sUniversity%20of%20Michigan!5e0!3m2!1sen!2sus!4v1693508255226!5m2!1sen!2sus"
