baseURL: https://blog.patrickli.one/
languageCode: en-us
title: PatrickLi.One
theme: "cactus"

params:
  description: "Hi I am Baichuan Li, a CS student @ University of Michigan. Contact me: public@patrickli.one"
  showProjectsList: true
  projectsUrl: "https://github.com/Gorgeous-Patrick"

