baseURL: https://www.patrickli.one/
languageCode: en-us
title: PatrickLi.One
theme: "PaperMod"

params:
    homeInfoParams:
        Title: PatrickLi.One
        Content: Baichuan Li
    socialIcons: # optional
        - name: "Gitea"
          url: "https://git.patrickli.one/patrickli"
        - name: "email"
          url: "mailto:public@patrickli.one"
        - name: "GitHub"
          url: "https://github.com/Gorgeous-Patrick"
